### ISSUE TITLE
Member Export Error when Asset field is used in blueprint

### ISSUE THREAD

**Issue by mikemartin** [jacksleight/statamic-memberbox#31]
## Bug Description
When exporting Members to CSV or JSON, an `Array to string conversion` is thrown for an asset field.

## How to Reproduce
Add an asset field to user blueprint and export Members.

For example:
```
-
  handle: photo
  field:
    type: assets
    display: Photo
    container: main
    folder: headshots
    max_files: 1
```

## Extra Detail
Error: https://flareapp.io/share/VmeMxBqm

## Environment
Environment
Application Name: Statamic
Laravel Version: 10.10.1
PHP Version: 8.1.17
Composer Version: 2.4.0
Environment: local
Debug Mode: ENABLED
URL: iveymbaa.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 2
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.11.0 PRO

Statamic Addons
jacksleight/statamic-memberbox: 2.0.1
statamic/migrator: dev-master
